SELECT D.AUTHOR_ID, D.AUTHOR_NAME, D.CATEGORY, SUM(TOTAL) AS TOTAL_SALES
FROM (SELECT A.BOOK_ID, A.CATEGORY, A.AUTHOR_ID, B.AUTHOR_NAME, SUM(C.SALES * A.PRICE) AS TOTAL
FROM BOOK A
LEFT JOIN AUTHOR B
ON A.AUTHOR_ID = B.AUTHOR_ID
LEFT JOIN BOOK_SALES C
ON A.BOOK_ID = C.BOOK_ID
WHERE YEAR(C.SALES_DATE) = 2022 AND MONTH(C.SALES_DATE) = 1
GROUP BY A.BOOK_ID) D
GROUP BY D.AUTHOR_ID, D.CATEGORY
ORDER BY D.AUTHOR_ID ASC, D.CATEGORY DESC