SELECT C.ID
FROM ECOLI_DATA A
LEFT JOIN (
    SELECT ID, PARENT_ID
    FROM ECOLI_DATA
) B
ON A.ID = B.PARENT_ID
LEFT JOIN (
    SELECT ID, PARENT_ID
    FROM ECOLI_DATA
) C
ON B.ID = C.PARENT_ID
WHERE A.PARENT_ID IS NULL AND C.PARENT_ID IS NOT NULL
ORDER BY C.ID ASC
