WITH DURATION AS (
    SELECT 
        B.HISTORY_ID,
        A.CAR_ID,
        A.CAR_TYPE,
        A.DAILY_FEE,
        DATEDIFF(END_DATE, START_DATE) + 1 AS DAY,
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE '할인 정책 없음'        
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR A
    RIGHT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON A.CAR_ID = B.CAR_ID
    WHERE A.CAR_TYPE = '트럭'
)

SELECT
    A.HISTORY_ID,
    FLOOR((A.DAILY_FEE - (A.DAILY_FEE * COALESCE(DISCOUNT_RATE / 100, 0))) * A.DAY) AS FEE
FROM DURATION A
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
ON A.DURATION_TYPE = B.DURATION_TYPE AND A.CAR_TYPE = B.CAR_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC