SELECT 
    B.EMP_NO, 
    B.EMP_NAME,
    CASE
        WHEN SUM(C.SCORE) / 2 >= 96 THEN 'S'
        WHEN SUM(C.SCORE) / 2 >= 90 THEN 'A'
        WHEN SUM(C.SCORE) / 2 >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN SUM(C.SCORE) / 2 >= 96 THEN SAL * 0.2
        WHEN SUM(C.SCORE) / 2 >= 90 THEN SAL * 0.15
        WHEN SUM(C.SCORE) / 2 >= 80 THEN SAL * 0.1
        ELSE SAL * 0
    END AS BONUS
FROM HR_DEPARTMENT A
RIGHT JOIN HR_EMPLOYEES B
ON A.DEPT_ID = B.DEPT_ID
LEFT JOIN HR_GRADE C
ON B.EMP_NO = C.EMP_NO
GROUP BY B.EMP_NO
ORDER BY B.EMP_NO ASC