SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE A
RIGHT JOIN REST_REVIEW B
ON A.MEMBER_ID = B.MEMBER_ID
LEFT JOIN (
    SELECT MEMBER_ID, COUNT(REVIEW_ID) AS REVIEW_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID 
) AS C
ON B.MEMBER_ID = C.MEMBER_ID
WHERE REVIEW_COUNT = (
    SELECT MAX(REVIEW_COUNT)
    FROM (   
        SELECT MEMBER_ID, COUNT(REVIEW_ID) AS REVIEW_COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID 
    ) AS SUB
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC