SELECT C.ID, D.FISH_NAME, C.LENGTH
FROM FISH_INFO C 
LEFT JOIN (
    SELECT B.FISH_TYPE, B.FISH_NAME, MAX(A.LENGTH) AS MAX_LENGTH
    FROM FISH_INFO A
    LEFT JOIN FISH_NAME_INFO B
    ON A.FISH_TYPE = B.FISH_TYPE
    GROUP BY B.FISH_TYPE, B.FISH_NAME
) AS D
ON C.FISH_TYPE = D.FISH_TYPE
WHERE C.LENGTH = D.MAX_LENGTH
ORDER BY C.ID ASC